Repository Hi-lingual/Hilingual-Server, pull requests merged in 2025-07, with the labels that each got.

#8 [Init/7] Jenkinsfile 수정
  Jenkinsfile
  build.gradle
Labels: 💚INIT💚, 🐬시훈🐬

#10 [init]#9 무중단 배포 (블루/그린) 배포
  Jenkinsfile
  deploy.sh
  docker-compose.yml
  nginx/nginx.conf
  src/main/resources/application.yml
Labels: 🩷FEAT🩷, 🐬시훈🐬

#22 [feat] #20 에러 로깅 추가
  src/main/java/org/hilingual/advice/GlobalExceptionHandler.java
Labels: 🩷FEAT🩷, 🐰영주🐰

#35 [hotfix] #34 충돌 해결하다가 실수한 부분들 해결하기
  src/main/java/org/hilingual/domain/diaryfeedback/core/facade/DiaryFeedbackRetriever.java
  src/main/java/org/hilingual/domain/diaryfeedback/core/facade/DiaryFeedbackSaver.java
  src/main/java/org/hilingual/domain/recommend/api/service/RecommendService.java
  src/main/java/org/hilingual/domain/recommend/core/domain/Recommend.java
  src/main/java/org/hilingual/domain/user/api/exception/UserApiException.java
  src/main/java/org/hilingual/domain/user/core/domain/User.java
Labels: 🔧FIX🔧, 🐰영주🐰

#43 [feat] #42 특정단어 세부내용조회 API 구현
  src/main/java/org/hilingual/domain/voca/api/controller/VocaController.java
  src/main/java/org/hilingual/domain/voca/api/dto/res/VocaDetailResponse.java
  src/main/java/org/hilingual/domain/voca/api/service/VocaService.java
  src/main/java/org/hilingual/domain/voca/core/exception/VocaCoreErrorCode.java
  src/main/java/org/hilingual/domain/voca/core/exception/VocaNotFoundException.java
  src/main/java/org/hilingual/domain/voca/core/facade/VocaRetriever.java
  src/main/java/org/hilingual/domain/voca/core/repository/VocaRepository.java
Labels: 🩷FEAT🩷, 🐬시훈🐬

#46 [feat] #44 작성된 일기 썸네일 조회 API 구현
  src/main/java/org/hilingual/advice/GlobalExceptionHandler.java
  src/main/java/org/hilingual/domain/diary/core/repository/DiaryRepository.java
  src/main/java/org/hilingual/domain/usercalendar/api/controller/UserCalendarController.java
  src/main/java/org/hilingual/domain/usercalendar/api/dto/res/UserCalendarDiarySummaryResponse.java
  src/main/java/org/hilingual/domain/usercalendar/api/exception/FutureDateNotAllowedException.java
  src/main/java/org/hilingual/domain/usercalendar/api/exception/UserCalendarApiErrorCode.java
  src/main/java/org/hilingual/domain/usercalendar/api/exception/UserCalendarApiException.java
  src/main/java/org/hilingual/domain/usercalendar/api/exception/UserCalendarBaseException.java
  src/main/java/org/hilingual/domain/usercalendar/api/exception/UserCalendarDiaryNotFoundException.java
  src/main/java/org/hilingual/domain/usercalendar/api/exception/UserCalendarInvalidDateFormatException.java
  src/main/java/org/hilingual/domain/usercalendar/api/service/UserCalendarService.java
  src/main/java/org/hilingual/domain/usercalendar/core/domain/UserCalendar.java
  src/main/java/org/hilingual/domain/usercalendar/core/domain/UserCalendarTableConstants.java
  src/main/java/org/hilingual/domain/usercalendar/core/exception/UserCalendarCoreErrorCode.java
  src/main/java/org/hilingual/domain/usercalendar/core/exception/UserCalendarCoreException.java
  src/main/java/org/hilingual/domain/usercalendar/core/exception/UserCalendarDiaryNotFoundException.java
  src/main/java/org/hilingual/domain/usercalendar/core/facade/UserCalendarRetriever.java
Labels: 🩷FEAT🩷, 🐬시훈🐬

#47 [feat] #45 AI 가 쓴 일기 확인 GET API 구현
  src/main/java/org/hilingual/domain/diary/api/controller/DiaryController.java
  src/main/java/org/hilingual/domain/diary/api/dto/res/DiaryDetails.java
  src/main/java/org/hilingual/domain/diary/api/service/DiaryService.java
  src/main/java/org/hilingual/domain/diaryfeedback/api/service/diff/DiaryDiffService.java
  src/main/java/org/hilingual/domain/diaryfeedback/api/service/diff/DiaryFeedbackPrompt.java
  src/main/java/org/hilingual/domain/diaryfeedback/api/service/diff/data/WordExtractor.java
  src/main/java/org/hilingual/domain/diaryfeedback/api/service/diff/data/WordInfo.java
  src/main/java/org/hilingual/domain/diaryfeedback/api/service/diff/extractor/DiffRangeExtractor.java
  src/main/java/org/hilingual/domain/diaryfeedback/api/service/diff/logic/DiffOperation.java
  src/main/java/org/hilingual/domain/diaryfeedback/api/service/diff/logic/DiffOperationMerger.java
  src/main/java/org/hilingual/domain/diaryfeedback/api/service/diff/logic/DiffProcessor.java
  src/main/java/org/hilingual/domain/diaryfeedback/api/service/diff/logic/DiffType.java
Labels: 🩷FEAT🩷, 🐰영주🐰

#51 [feat] #48 작성되지 않은 일기 주제 조회 API
  src/main/java/org/hilingual/common/domain/Topic.java
  src/main/java/org/hilingual/common/repository/TopicRepository.java
  src/main/java/org/hilingual/domain/usercalendar/api/controller/UserCalendarController.java
  src/main/java/org/hilingual/domain/usercalendar/api/dto/res/UserCalendarTopicResponse.java
  src/main/java/org/hilingual/domain/usercalendar/api/service/UserCalendarService.java
  src/main/java/org/hilingual/domain/usercalendar/core/exception/UserCalendarCoreErrorCode.java
  src/main/java/org/hilingual/domain/usercalendar/core/exception/UserCalendarTopicNotFoundException.java
  src/main/java/org/hilingual/domain/usercalendar/core/facade/UserCalendarRetriever.java
Labels: 🩷FEAT🩷, 🐬시훈🐬

#57 [feat] APPLE 로그인 연결
  build.gradle
  src/main/java/org/hilingual/auth/api/controller/AuthController.java
  src/main/java/org/hilingual/auth/api/dto/res/ApplePublicKeyResponse.java
  src/main/java/org/hilingual/auth/api/dto/res/AppleTokenResponse.java
  src/main/java/org/hilingual/auth/api/service/AuthService.java
  src/main/java/org/hilingual/auth/api/service/MyKeyLocator.java
  src/main/java/org/hilingual/domain/token/api/service/JwtProvider.java
  src/main/resources/application.yml
Labels: 🩷FEAT🩷, 🐶지은🐶

#59 [feat] #33 북마크 지정/해제 API
  src/main/java/org/hilingual/advice/GlobalExceptionHandler.java
  src/main/java/org/hilingual/common/exception/code/GlobalErrorCode.java
  src/main/java/org/hilingual/domain/recommend/api/controller/RecommendController.java
  src/main/java/org/hilingual/domain/recommend/api/dto/req/BookmarkRequest.java
  src/main/java/org/hilingual/domain/recommend/api/exception/RecommendBaseException.java
  src/main/java/org/hilingual/domain/recommend/api/service/RecommendService.java
  src/main/java/org/hilingual/domain/recommend/core/domain/Recommend.java
  src/main/java/org/hilingual/domain/recommend/core/exception/RecommendCoreErrorCode.java
  src/main/java/org/hilingual/domain/recommend/core/exception/RecommendCoreException.java
  src/main/java/org/hilingual/domain/recommend/core/exception/RecommendNotFoundException.java
  src/main/java/org/hilingual/domain/recommend/core/facade/RecommendRetriever.java
  src/main/java/org/hilingual/domain/voca/core/domain/Voca.java
  src/main/java/org/hilingual/domain/voca/core/facade/VocaRemover.java
  src/main/java/org/hilingual/domain/voca/core/facade/VocaSaver.java
  src/main/java/org/hilingual/domain/voca/core/repository/VocaRepository.java
Labels: 🩷FEAT🩷, 🐰영주🐰

#67 [feat] #54 월별 조회 API 구현 및 잘못된 월 입력 형식 예외처리
  src/main/java/org/hilingual/domain/usercalendar/api/controller/UserCalendarController.java
  src/main/java/org/hilingual/domain/usercalendar/api/dto/res/UserCalendarMonthlyResponse.java
  src/main/java/org/hilingual/domain/usercalendar/api/exception/InvalidMonthException.java
  src/main/java/org/hilingual/domain/usercalendar/api/exception/UserCalendarApiErrorCode.java
  src/main/java/org/hilingual/domain/usercalendar/api/service/UserCalendarService.java
  src/main/java/org/hilingual/domain/usercalendar/core/facade/UserCalendarRetriever.java
  src/main/java/org/hilingual/domain/usercalendar/core/repository/UserCalendarRepository.java
Labels: 🩷FEAT🩷, 🐬시훈🐬

#70 [fix] #69 RecommendBaseException 처리
  src/main/java/org/hilingual/advice/GlobalExceptionHandler.java
Labels: 🩷FEAT🩷, 🐰영주🐰

#72 [fix] #71 특정 단어 세부내용 조회 API 에서 phraseId 로 조회할 수 있도록 변경
  src/main/java/org/hilingual/domain/voca/api/controller/VocaController.java
  src/main/java/org/hilingual/domain/voca/api/service/VocaService.java
  src/main/java/org/hilingual/domain/voca/core/exception/VocaCoreErrorCode.java
  src/main/java/org/hilingual/domain/voca/core/facade/VocaRetriever.java
  src/main/java/org/hilingual/domain/voca/core/repository/VocaRepository.java
Labels: 🔧FIX🔧, 🐰영주🐰

#87 [fix] #84 응답필드 creaetedAt -> writtenDate
  src/main/java/org/hilingual/domain/voca/api/dto/res/VocaDetailResponse.java
  src/main/java/org/hilingual/domain/voca/core/repository/VocaRepository.java
Labels: 🔧FIX🔧

#93 [feat] #90 일기 쓰면서 UserCalendar 에도 기록되도록 수정 및 하루에 한 번만 일기 쓸 수 있도록 검증
  src/main/java/org/hilingual/advice/GlobalExceptionHandler.java
  src/main/java/org/hilingual/domain/diary/api/service/DiaryService.java
  src/main/java/org/hilingual/domain/diary/core/exception/AlreadyWrittenDiaryException.java
  src/main/java/org/hilingual/domain/diary/core/exception/DiaryCoreErrorCode.java
  src/main/java/org/hilingual/domain/diary/core/facade/DiaryRetriever.java
  src/main/java/org/hilingual/domain/diary/core/repository/DiaryRepository.java
  src/main/java/org/hilingual/domain/usercalendar/api/service/UserCalendarService.java
  src/main/java/org/hilingual/domain/usercalendar/core/domain/UserCalendar.java
  src/main/java/org/hilingual/domain/usercalendar/core/facade/UserCalendarRetriever.java
  src/main/java/org/hilingual/domain/usercalendar/core/repository/UserCalendarRepository.java
Labels: 🩷FEAT🩷, 🐰영주🐰

#98 [fix] #97 일기조회 createdAt->writtenDate로 변경
  src/main/java/org/hilingual/domain/diary/core/repository/DiaryRepository.java
  src/main/java/org/hilingual/domain/usercalendar/core/facade/UserCalendarRetriever.java
Labels: 🔧FIX🔧, 🐬시훈🐬

#103 [refac] #102 작성한 일기 썸네일 조회 API S3 절대경로로 수정
  src/main/java/org/hilingual/domain/usercalendar/api/service/UserCalendarService.java
Labels: 🧐REFACTOR🧐, 🐬시훈🐬

#107 [fix] 2차 QA 서버 보완사항 반영
  src/main/java/org/hilingual/domain/user/api/service/UserService.java
Labels: 🔧FIX🔧, 🐶지은🐶

#110 [hotfix] #96 토큰 재발급 시 다른 유저로 로그인되는 이슈 수정
  src/main/java/org/hilingual/domain/token/api/constants/TokenConstants.java
  src/main/java/org/hilingual/domain/token/api/service/RefreshTokenService.java
Labels: 🐶지은🐶, 🎁HOTFIX🎁

#111 [fix] #109 북마크 해제 시에도 새로고침 전에 단어 상세조회 가능하도록 로직 수정
  src/main/java/org/hilingual/domain/recommend/core/facade/RecommendRetriever.java
  src/main/java/org/hilingual/domain/recommend/core/repository/RecommendRepository.java
  src/main/java/org/hilingual/domain/voca/api/dto/res/VocaDetailResponse.java
  src/main/java/org/hilingual/domain/voca/api/service/VocaService.java
  src/main/java/org/hilingual/domain/voca/core/facade/VocaRetriever.java
  src/main/java/org/hilingual/domain/voca/core/repository/VocaRepository.java
Labels: 🔧FIX🔧, 🐰영주🐰
