Repository Hi-lingual/Hilingual-Server, pull requests merged in 2025-08, with the labels that each got.

#124 [refac] #122 CI/CD 파이프라인 재구축
  .github/workflows/dev-deploy.yml
  .github/workflows/pr-ci.yml
  .github/workflows/prod-deploy.yml
  Jenkinsfile
  deploy.sh
  docker-compose.yml
  nginx/.env
  nginx/docker-compose.yml
  nginx/nginx.template.conf
  nginx/start-nginx.sh
Labels: 🧐REFACTOR🧐, 🐬시훈🐬

#133 [fix] #131 MySql -> PostgreSql 의존성 변경 및 application.yml 최신화
  hilingual-api/src/main/resources/application.yml
  hilingual-domain/build.gradle
Labels: 🔧FIX🔧, 🐰영주🐰

#138 [refac] #137 nginx 수정 및 모니터링 고려 배포 스크립트 추가
  .github/workflows/dev-deploy.yml
  .github/workflows/prod-deploy.yml
  nginx/nginx.template.conf
  nginx/start-nginx.sh
Labels: 🐬시훈🐬

#134 [refac] #132 도메인별 BaseException 없애고 전체 HilingualBaseException 기반 전역 예외 처리
  build.gradle
  hilingual-api/src/main/java/org/sopt/controller/diary/exception/DiaryApiException.java
  hilingual-api/src/main/java/org/sopt/controller/user/exception/UserApiException.java
  hilingual-api/src/main/java/org/sopt/controller/usercalendar/exception/UserCalendarApiException.java
  hilingual-api/src/main/java/org/sopt/controller/voca/exception/VocaApiException.java
  hilingual-api/src/main/java/org/sopt/exception/GlobalExceptionHandler.java
  hilingual-auth/src/main/java/org/sopt/exception/AuthApiException.java
  hilingual-auth/src/main/java/org/sopt/exception/AuthBaseException.java
  hilingual-auth/src/main/java/org/sopt/exception/AuthCoreException.java
  hilingual-auth/src/main/java/org/sopt/exception/GoogleAuthUnAuthorizedException.java
  hilingual-auth/src/main/java/org/sopt/jwt/exception/JwtApiException.java
  hilingual-auth/src/main/java/org/sopt/jwt/exception/JwtBaseException.java
  hilingual-auth/src/main/java/org/sopt/jwt/exception/JwtCoreException.java
  hilingual-auth/src/main/java/org/sopt/jwt/exception/UnauthorizedException.java
  hilingual-common/src/main/java/org/sopt/exception/base/HilingualBaseException.java
  hilingual-domain/src/main/java/org/sopt/diary/exception/DiaryAlreadyWrittenException.java
  hilingual-domain/src/main/java/org/sopt/diary/exception/DiaryBaseException.java
  hilingual-domain/src/main/java/org/sopt/diary/exception/DiaryCoreException.java
  hilingual-domain/src/main/java/org/sopt/diary/facade/DiaryRetriever.java
  hilingual-domain/src/main/java/org/sopt/recommend/exception/RecommendBaseException.java
  hilingual-domain/src/main/java/org/sopt/recommend/exception/RecommendCoreException.java
  hilingual-domain/src/main/java/org/sopt/recommend/exception/VocaBaseException.java
  hilingual-domain/src/main/java/org/sopt/user/exception/UserBaseException.java
  hilingual-domain/src/main/java/org/sopt/user/exception/UserCoreException.java
  hilingual-domain/src/main/java/org/sopt/usercalendar/exception/UserCalendarBaseException.java
  hilingual-domain/src/main/java/org/sopt/usercalendar/exception/UserCalendarCoreException.java
  hilingual-domain/src/main/java/org/sopt/usercalendar/exception/UserCalendarDiaryNotFoundException.java
  hilingual-domain/src/main/java/org/sopt/userprofile/exception/UserProfileBaseException.java
  hilingual-domain/src/main/java/org/sopt/userprofile/exception/UserProfileCoreException.java
  hilingual-domain/src/main/java/org/sopt/voca/exception/VocaCoreException.java
  hilingual-external/src/main/java/org/sopt/aws/s3/exception/InvalidImageException.java
  hilingual-external/src/main/java/org/sopt/aws/s3/exception/S3ApiException.java
  hilingual-external/src/main/java/org/sopt/aws/s3/exception/S3BaseException.java
  hilingual-external/src/main/java/org/sopt/openai/exception/OpenAIApiException.java
  hilingual-external/src/main/java/org/sopt/openai/exception/OpenAIBaseException.java
Labels: 🧐REFACTOR🧐, 🐰영주🐰

#140 [refac] #139 nginx 인스턴스 docker compose 버전(v1)에 맞게 sh 수정
  .github/workflows/dev-deploy.yml
  .github/workflows/prod-deploy.yml
Labels: 🔧FIX🔧, 🐬시훈🐬

#148 [feat] #141 2차 스프린트 변경/추가된 Entity 구현
  hilingual-api/src/main/java/org/sopt/HilingualApplication.java
  hilingual-api/src/main/java/org/sopt/controller/userprofile/service/UserProfileService.java
  hilingual-domain/src/main/java/org/sopt/alarmpreference/domain/AlarmPreference.java
  hilingual-domain/src/main/java/org/sopt/alarmpreference/domain/AlarmPreferenceTableConstants.java
  hilingual-domain/src/main/java/org/sopt/alarmpreference/type/AlarmType.java
  hilingual-domain/src/main/java/org/sopt/alarmpreference/type/AlarmTypeConverter.java
  hilingual-domain/src/main/java/org/sopt/block/Block.java
  hilingual-domain/src/main/java/org/sopt/block/BlockTableConstants.java
  hilingual-domain/src/main/java/org/sopt/diary/domain/Diary.java
  hilingual-domain/src/main/java/org/sopt/diary/domain/DiaryTableConstants.java
  hilingual-domain/src/main/java/org/sopt/feedalarm/domain/FeedAlarm.java
  hilingual-domain/src/main/java/org/sopt/feedalarm/domain/FeedAlarmTableConstants.java
  hilingual-domain/src/main/java/org/sopt/feedalarm/type/FeedAlarmType.java
  hilingual-domain/src/main/java/org/sopt/feedalarm/type/FeedAlarmTypeConverter.java
  hilingual-domain/src/main/java/org/sopt/feedalarm/type/TargetType.java
  hilingual-domain/src/main/java/org/sopt/feedalarm/type/TargetTypeConverter.java
  hilingual-domain/src/main/java/org/sopt/follow/Follow.java
  hilingual-domain/src/main/java/org/sopt/follow/FollowTableConstants.java
  hilingual-domain/src/main/java/org/sopt/forbiddenword/domain/ForbiddenWord.java
  hilingual-domain/src/main/java/org/sopt/likeddiary/LikedDiary.java
  hilingual-domain/src/main/java/org/sopt/likeddiary/LikedDiaryTableConstants.java
  hilingual-domain/src/main/java/org/sopt/notice/domain/Notice.java
  hilingual-domain/src/main/java/org/sopt/notice/domain/NoticeTableConstants.java
  hilingual-domain/src/main/java/org/sopt/notice/type/Category.java
  hilingual-domain/src/main/java/org/sopt/notice/type/CategoryConverter.java
  hilingual-domain/src/main/java/org/sopt/noticedelivery/domain/NoticeDelivery.java
  hilingual-domain/src/main/java/org/sopt/noticedelivery/domain/NoticeDeliveryTableConstants.java
  hilingual-domain/src/main/java/org/sopt/noticedetail/domain/NoticeDetail.java
  hilingual-domain/src/main/java/org/sopt/noticedetail/domain/NoticeDetailTableConstants.java
  hilingual-domain/src/main/java/org/sopt/user/domain/User.java
  hilingual-domain/src/main/java/org/sopt/user/domain/UserTableConstants.java
  hilingual-domain/src/main/java/org/sopt/user/type/RegisterStatus.java
  hilingual-domain/src/main/java/org/sopt/user/type/RegisterStatusConverter.java
  hilingual-domain/src/main/java/org/sopt/userprofile/domain/UserProfile.java
  hilingual-domain/src/main/java/org/sopt/userprofile/domain/UserProfileTableConstants.java
  hilingual-domain/src/main/java/org/sopt/voca/domain/Voca.java
  hilingual-domain/src/main/java/org/sopt/voca/domain/VocaTableConstants.java
  hilingual-domain/src/main/java/org/sopt/voca/type/SaveRoot.java
  hilingual-domain/src/main/java/org/sopt/voca/type/SaveRootConverter.java
Labels: 🩷FEAT🩷, 🐶지은🐶

#150 [feat] #149 유저 차단/차단 해제 API 구현
  hilingual-api/src/main/java/org/sopt/controller/block/api/BlockController.java
  hilingual-api/src/main/java/org/sopt/controller/block/exception/BlockApiErrorCode.java
  hilingual-api/src/main/java/org/sopt/controller/block/exception/BlockApiException.java
  hilingual-api/src/main/java/org/sopt/controller/block/exception/CannotSelfBlockException.java
  hilingual-api/src/main/java/org/sopt/controller/block/exception/CannotSelfUnblockException.java
  hilingual-api/src/main/java/org/sopt/controller/block/service/BlockService.java
  hilingual-api/src/main/resources/application.yml
  hilingual-domain/src/main/java/org/sopt/block/domain/Block.java
  hilingual-domain/src/main/java/org/sopt/block/domain/BlockTableConstants.java
  hilingual-domain/src/main/java/org/sopt/block/exception/AlreadyBlockedUserException.java
  hilingual-domain/src/main/java/org/sopt/block/exception/BlockCoreErrorCode.java
  hilingual-domain/src/main/java/org/sopt/block/exception/BlockCoreException.java
  hilingual-domain/src/main/java/org/sopt/block/exception/BlockedNotFoundException.java
  hilingual-domain/src/main/java/org/sopt/block/exception/UnblockableUserException.java
  hilingual-domain/src/main/java/org/sopt/block/facade/BlockFacade.java
  hilingual-domain/src/main/java/org/sopt/block/facade/BlockRetriever.java
  hilingual-domain/src/main/java/org/sopt/block/facade/BlockSaver.java
  hilingual-domain/src/main/java/org/sopt/block/repository/BlockRepository.java
  hilingual-domain/src/main/java/org/sopt/follow/domain/Follow.java
  hilingual-domain/src/main/java/org/sopt/follow/domain/FollowTableConstants.java
  hilingual-domain/src/main/java/org/sopt/user/facade/UserFacade.java
  hilingual-domain/src/main/java/org/sopt/user/facade/UserRetriever.java
  hilingual-domain/src/main/java/org/sopt/user/repository/UserRepository.java
Labels: 🩷FEAT🩷, 🐶지은🐶

#152 [feat] #151 차단한 계정 목록 조회 API 구현
  hilingual-api/src/main/java/org/sopt/controller/block/api/BlockController.java
  hilingual-api/src/main/java/org/sopt/controller/block/service/BlockService.java
  hilingual-api/src/main/java/org/sopt/controller/userprofile/dto/UserProfileSummaryDtoRes.java
  hilingual-domain/src/main/java/org/sopt/block/domain/Block.java
  hilingual-domain/src/main/java/org/sopt/block/domain/BlockTableConstants.java
  hilingual-domain/src/main/java/org/sopt/block/facade/BlockFacade.java
  hilingual-domain/src/main/java/org/sopt/block/facade/BlockRetriever.java
  hilingual-domain/src/main/java/org/sopt/block/repository/BlockRepository.java
  hilingual-domain/src/main/java/org/sopt/userprofile/facade/UserProfileFacade.java
  hilingual-domain/src/main/java/org/sopt/userprofile/facade/UserProfileRetriever.java
  hilingual-domain/src/main/java/org/sopt/userprofile/repository/UserProfileRepository.java
Labels: 🩷FEAT🩷, 🐶지은🐶

#156 [feat] #145 Token 엔티티 및 TokenRepository 구현
  hilingual-api/src/main/java/org/sopt/HilingualApplication.java
  hilingual-api/src/main/java/org/sopt/config/RedisConfig.java
  hilingual-api/src/main/java/org/sopt/controller/test/api/JwtController.java
  hilingual-api/src/main/java/org/sopt/controller/test/dto/jwt/IssueTokenRequest.java
  hilingual-auth/src/main/java/org/sopt/jwt/auth/domain/DeviceType.java
  hilingual-auth/src/main/java/org/sopt/jwt/auth/domain/Token.java
  hilingual-auth/src/main/java/org/sopt/jwt/auth/domain/TokenRepository.java
  hilingual-domain/src/main/java/org/sopt/diary/domain/Diary.java
Labels: 🩷FEAT🩷, 🐰영주🐰

#172 [fix] #171 AuthBaseException이 HilingualBaseException 상속하도록 수정
  hilingual-auth/src/main/java/org/sopt/exception/AuthBaseException.java
Labels: 🔧FIX🔧, 🐰영주🐰

#166 [feat] #121 내 정보 확인, 기본 정보 조회 API 구현
  hilingual-api/src/main/java/org/sopt/controller/user/api/UserController.java
  hilingual-api/src/main/java/org/sopt/controller/user/dto/HomeUserProfileRes.java
  hilingual-api/src/main/java/org/sopt/controller/user/dto/UserDefaultInfoRes.java
  hilingual-api/src/main/java/org/sopt/controller/user/exception/CannotLoadProviderException.java
  hilingual-api/src/main/java/org/sopt/controller/user/exception/UserApiErrorCode.java
  hilingual-api/src/main/java/org/sopt/controller/user/service/UserService.java
  hilingual-api/src/main/java/org/sopt/controller/userprofile/api/UserProfileController.java
  hilingual-api/src/main/java/org/sopt/controller/userprofile/service/UserProfileService.java
  hilingual-domain/src/main/java/org/sopt/userprofile/domain/UserProfile.java
  hilingual-domain/src/main/java/org/sopt/userprofile/dto/UserProfileRes.java
  hilingual-domain/src/main/java/org/sopt/userprofile/facade/UserProfileFacade.java
  hilingual-domain/src/main/java/org/sopt/userprofile/facade/UserProfileRetriever.java
Labels: 🩷FEAT🩷, 🐶지은🐶

#173 [refac] #167 차단 목록 조회, 차단/차단 해제 API 코드리뷰 반영 및 코드 구조 개선
  hilingual-api/src/main/java/org/sopt/controller/block/api/BlockController.java
  hilingual-api/src/main/java/org/sopt/controller/block/service/BlockService.java
  hilingual-api/src/main/java/org/sopt/controller/follow/dto/FollowerDtoRes.java
  hilingual-api/src/main/java/org/sopt/controller/follow/dto/FollowingDtoRes.java
  hilingual-api/src/main/java/org/sopt/controller/follow/service/FollowService.java
  hilingual-api/src/main/java/org/sopt/controller/userprofile/dto/UserProfileSummaryRes.java
  hilingual-domain/src/main/java/org/sopt/block/domain/Block.java
  hilingual-domain/src/main/java/org/sopt/block/domain/BlockTableConstants.java
  hilingual-domain/src/main/java/org/sopt/block/facade/BlockSaver.java
  hilingual-domain/src/main/java/org/sopt/block/repository/BlockRepository.java
Labels: 🧐REFACTOR🧐, 🐶지은🐶

#160 [feat] #158 토큰 재발급 API 구현
  hilingual-api/build.gradle
  hilingual-api/src/main/java/org/sopt/config/SecurityConfig.java
  hilingual-api/src/main/java/org/sopt/controller/test/api/JwtController.java
  hilingual-api/src/main/java/org/sopt/controller/test/dto/jwt/IssueTokenRequest.java
  hilingual-api/src/main/java/org/sopt/controller/token/TokenService.java
  hilingual-api/src/main/java/org/sopt/controller/user/api/UserController.java
  hilingual-api/src/main/java/org/sopt/controller/user/service/UserService.java
  hilingual-auth/src/main/java/org/sopt/exception/AuthErrorCode.java
  hilingual-auth/src/main/java/org/sopt/exception/InvalidAuthHeaderException.java
  hilingual-auth/src/main/java/org/sopt/exception/InvalidSecretKeyException.java
  hilingual-auth/src/main/java/org/sopt/exception/InvalidTokenException.java
  hilingual-auth/src/main/java/org/sopt/exception/TokenHashingException.java
  hilingual-auth/src/main/java/org/sopt/exception/TokenNotFoundException.java
  hilingual-auth/src/main/java/org/sopt/jwt/auth/authentication/UserAuthentication.java
  hilingual-auth/src/main/java/org/sopt/jwt/auth/authentication/UserAuthenticationFactory.java
  hilingual-auth/src/main/java/org/sopt/jwt/auth/domain/Token.java
  hilingual-auth/src/main/java/org/sopt/jwt/auth/domain/TokenRepository.java
  hilingual-auth/src/main/java/org/sopt/jwt/auth/domain/type/AuthProvider.java
  hilingual-auth/src/main/java/org/sopt/jwt/auth/domain/type/DeviceType.java
  hilingual-auth/src/main/java/org/sopt/jwt/auth/dto/ReissueTokensRes.java
  hilingual-auth/src/main/java/org/sopt/jwt/auth/web/JwtAuthenticationEntryPoint.java
  hilingual-auth/src/main/java/org/sopt/jwt/auth/web/JwtAuthenticationFilter.java
  hilingual-auth/src/main/java/org/sopt/jwt/core/JwtClaimsKeys.java
  hilingual-auth/src/main/java/org/sopt/jwt/core/JwtTokenProvider.java
  hilingual-auth/src/main/java/org/sopt/jwt/core/TokenHasher.java
  hilingual-auth/src/main/java/org/sopt/jwt/core/TokenId.java
  hilingual-auth/src/main/java/org/sopt/jwt/support/AuthConstants.java
  hilingual-auth/src/main/java/org/sopt/jwt/support/SecurityUtils.java
  hilingual-auth/src/main/java/org/sopt/jwt/support/logsupport/ErrorResponder.java
  hilingual-domain/src/main/java/org/sopt/user/domain/User.java
Labels: 🩷FEAT🩷, 🐰영주🐰

#170 [feat] #142 Presgined Url 발급 API 구현 (일기 피드백 요청 API, AI가 교정한 일기 확인 API 포함)
  hilingual-api/src/main/java/org/sopt/controller/diary/api/DiaryController.java
  hilingual-api/src/main/java/org/sopt/controller/diary/dto/CreateDiaryReq.java
  hilingual-api/src/main/java/org/sopt/controller/diary/dto/DiaryRes.java
  hilingual-api/src/main/java/org/sopt/controller/diary/service/DiaryService.java
  hilingual-api/src/main/java/org/sopt/controller/external/S3Controller.java
  hilingual-api/src/main/java/org/sopt/controller/external/UploadPurposeReq.java
  hilingual-api/src/main/java/org/sopt/controller/test/api/ImageController.java
  hilingual-api/src/main/resources/application.yml
  hilingual-domain/src/main/java/org/sopt/usercalendar/domain/UserCalendar.java
  hilingual-external/src/main/java/org/sopt/aws/config/AWSConfig.java
  hilingual-external/src/main/java/org/sopt/aws/config/AWSProperties.java
  hilingual-external/src/main/java/org/sopt/aws/s3/dto/PreSignedUrlRes.java
  hilingual-external/src/main/java/org/sopt/aws/s3/dto/Purpose.java
  hilingual-external/src/main/java/org/sopt/aws/s3/exception/S3ApiException.java
  hilingual-external/src/main/java/org/sopt/aws/s3/exception/S3BaseException.java
  hilingual-external/src/main/java/org/sopt/aws/s3/exception/S3ErrorCode.java
  hilingual-external/src/main/java/org/sopt/aws/s3/exception/S3SuccessCode.java
  hilingual-external/src/main/java/org/sopt/aws/s3/service/S3Service.java
  hilingual-external/src/main/java/org/sopt/aws/s3/utils/S3Service.java
Labels: 🩷FEAT🩷, 🐰영주🐰

#181 [feat] #176 피드 프로필 '공유한 일기', '공감한 일기' API 구현
  hilingual-api/src/main/java/org/sopt/controller/feed/api/FeedController.java
  hilingual-api/src/main/java/org/sopt/controller/feed/dto/LikedDiaryListRes.java
  hilingual-api/src/main/java/org/sopt/controller/feed/dto/SharedDiaryListRes.java
  hilingual-api/src/main/java/org/sopt/controller/feed/exception/FeedApiErrorCode.java
  hilingual-api/src/main/java/org/sopt/controller/feed/exception/FeedApiException.java
  hilingual-api/src/main/java/org/sopt/controller/feed/service/FeedService.java
  hilingual-domain/src/main/java/org/sopt/diary/domain/Diary.java
  hilingual-domain/src/main/java/org/sopt/diary/facade/DiaryFacade.java
  hilingual-domain/src/main/java/org/sopt/diary/facade/DiaryRetriever.java
  hilingual-domain/src/main/java/org/sopt/diary/repository/DiaryRepository.java
  hilingual-domain/src/main/java/org/sopt/likeddiary/domain/LikedDiary.java
  hilingual-domain/src/main/java/org/sopt/likeddiary/domain/LikedDiaryTableConstants.java
  hilingual-domain/src/main/java/org/sopt/likeddiary/facade/LikedDiaryFacade.java
  hilingual-domain/src/main/java/org/sopt/likeddiary/facade/LikedDiaryRetriever.java
  hilingual-domain/src/main/java/org/sopt/likeddiary/repository/LikedDiaryRepository.java
  hilingual-domain/src/main/java/org/sopt/userprofile/domain/UserProfile.java
Labels: 🩷FEAT🩷, 🐶지은🐶

#189 [feat] #188 북마크 지정/해제 API 에서 단어 저장 경로 나누기
  hilingual-api/src/main/java/org/sopt/controller/recommend/api/RecommendController.java
  hilingual-api/src/main/java/org/sopt/controller/recommend/exception/RecommendApiErrorCode.java
  hilingual-api/src/main/java/org/sopt/controller/recommend/exception/RecommendApiException.java
  hilingual-api/src/main/java/org/sopt/controller/recommend/exception/RecommendForbiddenException.java
  hilingual-api/src/main/java/org/sopt/controller/recommend/service/RecommendService.java
  hilingual-api/src/main/java/org/sopt/controller/voca/dto/res/VocaDetailResponse.java
  hilingual-api/src/main/java/org/sopt/controller/voca/dto/res/VocaSearchListResponse.java
  hilingual-api/src/main/java/org/sopt/controller/voca/service/VocaService.java
  hilingual-domain/src/main/java/org/sopt/recommend/domain/Recommend.java
  hilingual-domain/src/main/java/org/sopt/voca/domain/Voca.java
  hilingual-domain/src/main/java/org/sopt/voca/domain/VocaTableConstants.java
  hilingual-domain/src/main/java/org/sopt/voca/dto/VocaItemRes.java
  hilingual-domain/src/main/java/org/sopt/voca/facade/VocaFacade.java
  hilingual-domain/src/main/java/org/sopt/voca/facade/VocaRemover.java
  hilingual-domain/src/main/java/org/sopt/voca/facade/VocaRetriever.java
  hilingual-domain/src/main/java/org/sopt/voca/facade/VocaSaver.java
  hilingual-domain/src/main/java/org/sopt/voca/repository/VocaRepository.java
Labels: 🩷FEAT🩷, 🐰영주🐰

#185 [feat] #179 일기 게시(공개)하기/비공개하기 API 구현
  hilingual-api/src/main/java/org/sopt/controller/diary/api/DiaryController.java
  hilingual-api/src/main/java/org/sopt/controller/diary/service/DiaryService.java
  hilingual-domain/src/main/java/org/sopt/diary/domain/Diary.java
  hilingual-domain/src/main/java/org/sopt/diary/facade/DiaryFacade.java
  hilingual-domain/src/main/java/org/sopt/diary/facade/DiaryRetriever.java
  hilingual-domain/src/main/java/org/sopt/diary/facade/DiaryUpdater.java
Labels: 🩷FEAT🩷, 🐰영주🐰

#207 [fix] #205 일기 소유자만 해당 일기를 공개/비공개 할 수 있도록 소유자 검증 로직 추가
  hilingual-api/src/main/java/org/sopt/controller/diary/service/DiaryService.java
  hilingual-api/src/main/java/org/sopt/controller/recommend/exception/RecommendApiErrorCode.java
Labels: 🔧FIX🔧, 🐰영주🐰

#199 [feat] #198 닉네임 검사 - 금지어 포함 여부 판단 API 구현
  hilingual-api/src/main/java/org/sopt/controller/user/api/UserController.java
  hilingual-api/src/main/java/org/sopt/controller/user/service/UserService.java
  hilingual-api/src/main/java/org/sopt/controller/userprofile/api/UserProfileController.java
  hilingual-api/src/main/java/org/sopt/controller/userprofile/exception/UserProfileSuccessCode.java
  hilingual-api/src/main/java/org/sopt/controller/userprofile/service/UserProfileService.java
  hilingual-domain/src/main/java/org/sopt/forbiddenword/domain/ForbiddenWord.java
  hilingual-domain/src/main/java/org/sopt/forbiddenword/facade/ForbiddenWordFacade.java
  hilingual-domain/src/main/java/org/sopt/forbiddenword/facade/ForbiddenWordRetriever.java
  hilingual-domain/src/main/java/org/sopt/forbiddenword/repository/ForbiddenWordRepository.java
  hilingual-domain/src/main/java/org/sopt/user/facade/UserFacade.java
  hilingual-domain/src/main/java/org/sopt/user/facade/UserRetriever.java
  hilingual-domain/src/main/java/org/sopt/userprofile/facade/UserProfileFacade.java
  hilingual-domain/src/main/java/org/sopt/userprofile/facade/UserProfileRetriever.java
Labels: 🩷FEAT🩷, 🐶지은🐶

#197 [feat] #196 사용자 검색하기 API 구현
  hilingual-api/src/main/java/org/sopt/controller/feed/api/FeedController.java
  hilingual-api/src/main/java/org/sopt/controller/feed/dto/UserListRes.java
  hilingual-api/src/main/java/org/sopt/controller/feed/service/FeedService.java
  hilingual-domain/src/main/java/org/sopt/userprofile/dto/UserSearchProjection.java
  hilingual-domain/src/main/java/org/sopt/userprofile/facade/UserProfileFacade.java
  hilingual-domain/src/main/java/org/sopt/userprofile/facade/UserProfileRetriever.java
  hilingual-domain/src/main/java/org/sopt/userprofile/repository/UserProfileRepository.java
Labels: 🩷FEAT🩷, 🐶지은🐶

#217 [feat] #208 공지 사항 알림 상세보기 API 구현
  hilingual-api/src/main/java/org/sopt/controller/user/api/UserController.java
  hilingual-api/src/main/java/org/sopt/controller/user/dto/NoticeDetailRes.java
  hilingual-api/src/main/java/org/sopt/controller/user/service/UserService.java
  hilingual-domain/src/main/java/org/sopt/notice/domain/Notice.java
  hilingual-domain/src/main/java/org/sopt/notice/domain/NoticeTableConstants.java
  hilingual-domain/src/main/java/org/sopt/noticedelivery/domain/NoticeDelivery.java
  hilingual-domain/src/main/java/org/sopt/noticedelivery/exception/NoticeDeliveryCoreException.java
  hilingual-domain/src/main/java/org/sopt/noticedelivery/exception/NoticeDeliveryErrorCode.java
  hilingual-domain/src/main/java/org/sopt/noticedelivery/exception/NoticeDeliveryNoFoundException.java
  hilingual-domain/src/main/java/org/sopt/noticedelivery/facade/NoticeDeliveryFacade.java
  hilingual-domain/src/main/java/org/sopt/noticedelivery/facade/NoticeDeliveryRetriever.java
  hilingual-domain/src/main/java/org/sopt/noticedelivery/repository/NoticeDeliveryRepository.java
  hilingual-domain/src/main/java/org/sopt/user/domain/User.java
  hilingual-domain/src/main/java/org/sopt/user/domain/UserTableConstants.java
Labels: 🩷FEAT🩷, 🐰영주🐰

#223 [feat] #221 알림 읽음 처리 API 구현
  hilingual-api/src/main/java/org/sopt/controller/user/api/UserController.java
  hilingual-api/src/main/java/org/sopt/controller/user/service/UserService.java
  hilingual-domain/src/main/java/org/sopt/feedalarm/domain/FeedAlarm.java
  hilingual-domain/src/main/java/org/sopt/feedalarm/exception/FeedAlarmCoreErrorCode.java
  hilingual-domain/src/main/java/org/sopt/feedalarm/exception/FeedAlarmNotFoundException.java
  hilingual-domain/src/main/java/org/sopt/feedalarm/facade/FeedAlarmFacade.java
  hilingual-domain/src/main/java/org/sopt/feedalarm/facade/FeedAlarmRetriever.java
  hilingual-domain/src/main/java/org/sopt/feedalarm/repository/FeedAlarmRepository.java
Labels: 🩷FEAT🩷, 🐰영주🐰
