Repository Hi-lingual/Hilingual-Server, pull requests merged in 2025-09, with the labels that each got.

#219 [feat] #215 프로필 사진 변경 API 구현
  hilingual-api/src/main/java/org/sopt/controller/userprofile/api/UserProfileController.java
  hilingual-api/src/main/java/org/sopt/controller/userprofile/dto/UserProfileImgReq.java
  hilingual-api/src/main/java/org/sopt/controller/userprofile/exception/UserProfileApiErrorCode.java
  hilingual-api/src/main/java/org/sopt/controller/userprofile/exception/UserProfileApiException.java
  hilingual-api/src/main/java/org/sopt/controller/userprofile/exception/UserProfileImagePurposeMismatchException.java
  hilingual-api/src/main/java/org/sopt/controller/userprofile/service/UserProfileService.java
  hilingual-domain/src/main/java/org/sopt/userprofile/facade/UserProfileFacade.java
  hilingual-domain/src/main/java/org/sopt/userprofile/facade/UserProfileUpdater.java
  hilingual-domain/src/main/java/org/sopt/userprofile/repository/UserProfileRepository.java
  hilingual-external/src/main/java/org/sopt/aws/s3/service/S3Service.java
Labels: 🩷FEAT🩷, 🐶지은🐶

#224 [feat] #195 소셜 로그인 API 구현 및 변경된 Spring Security에 맞추어 리팩토링
  hilingual-api/build.gradle
  hilingual-api/src/main/java/org/sopt/controller/auth/api/AuthController.java
  hilingual-api/src/main/java/org/sopt/controller/auth/dto/SocialLoginReq.java
  hilingual-api/src/main/java/org/sopt/controller/auth/dto/SocialLoginRes.java
  hilingual-api/src/main/java/org/sopt/controller/auth/exception/AppleServerErrorException.java
  hilingual-api/src/main/java/org/sopt/controller/auth/exception/AuthApiErrorCode.java
  hilingual-api/src/main/java/org/sopt/controller/auth/exception/AuthApiException.java
  hilingual-api/src/main/java/org/sopt/controller/auth/exception/GoogleServerErrorException.java
  hilingual-api/src/main/java/org/sopt/controller/auth/exception/InvalidAppleTokenException.java
  hilingual-api/src/main/java/org/sopt/controller/auth/exception/InvalidGoogleTokenException.java
  hilingual-api/src/main/java/org/sopt/controller/auth/exception/InvalidProviderException.java
  hilingual-api/src/main/java/org/sopt/controller/auth/service/AuthService.java
  hilingual-api/src/main/java/org/sopt/controller/auth/util/ApplePublicKeyList.java
  hilingual-api/src/main/java/org/sopt/controller/auth/util/GoogleOAuth2UserInfo.java
  hilingual-api/src/main/java/org/sopt/controller/auth/util/MyKeyLocator.java
  hilingual-api/src/main/java/org/sopt/controller/test/api/JwtController.java
  hilingual-api/src/main/java/org/sopt/controller/token/TokenService.java
  hilingual-api/src/main/java/org/sopt/controller/user/service/UserService.java
  hilingual-api/src/main/java/org/sopt/controller/userprofile/service/UserProfileService.java
  hilingual-auth/src/main/java/org/sopt/jwt/auth/web/JwtAuthenticationFilter.java
  hilingual-auth/src/main/java/org/sopt/jwt/support/AuthConstants.java
  hilingual-domain/src/main/java/org/sopt/user/domain/User.java
  hilingual-domain/src/main/java/org/sopt/user/domain/UserTableConstants.java
  hilingual-domain/src/main/java/org/sopt/user/facade/UserFacade.java
  hilingual-domain/src/main/java/org/sopt/user/facade/UserRetriever.java
  hilingual-domain/src/main/java/org/sopt/user/facade/UserSaver.java
  hilingual-domain/src/main/java/org/sopt/user/type/RegisterStatus.java
Labels: 🩷FEAT🩷, 🧐REFACTOR🧐, 🐶지은🐶

#228 [feat] #225 회원가입(프로필 등록) API 구현
  hilingual-api/src/main/java/org/sopt/controller/userprofile/api/UserProfileController.java
  hilingual-api/src/main/java/org/sopt/controller/userprofile/dto/UserProfileReq.java
  hilingual-api/src/main/java/org/sopt/controller/userprofile/service/UserProfileService.java
  hilingual-domain/src/main/java/org/sopt/alarmpreference/domain/AlarmPreference.java
  hilingual-domain/src/main/java/org/sopt/alarmpreference/domain/AlarmPreferenceTableConstants.java
  hilingual-domain/src/main/java/org/sopt/alarmpreference/facade/AlarmPreferenceFacade.java
  hilingual-domain/src/main/java/org/sopt/alarmpreference/facade/AlarmPreferenceSaver.java
  hilingual-domain/src/main/java/org/sopt/alarmpreference/repository/AlarmPreferenceRepository.java
Labels: 🩷FEAT🩷, 🐶지은🐶

#209 [feat] #200 추천 피드, 팔로잉 피드 조회 API 구현
  hilingual-api/src/main/java/org/sopt/controller/feed/api/FeedController.java
  hilingual-api/src/main/java/org/sopt/controller/feed/dto/FollowFeedListRes.java
  hilingual-api/src/main/java/org/sopt/controller/feed/dto/RecommendFeedListRes.java
  hilingual-api/src/main/java/org/sopt/controller/feed/service/FeedService.java
  hilingual-domain/src/main/java/org/sopt/feed/dto/FeedProjection.java
  hilingual-domain/src/main/java/org/sopt/feed/facade/FeedFacade.java
  hilingual-domain/src/main/java/org/sopt/feed/facade/FeedRetriever.java
  hilingual-domain/src/main/java/org/sopt/feed/repository/FeedRepository.java
  hilingual-domain/src/main/java/org/sopt/follow/facade/FollowFacade.java
  hilingual-domain/src/main/java/org/sopt/follow/facade/FollowRetriever.java
  hilingual-domain/src/main/java/org/sopt/follow/repository/FollowRepository.java
Labels: 🩷FEAT🩷, 🐶지은🐶

#206 [feat] #202 피드에서도 일기에 접근 가능하도록 관련된 3가지 API 들 수정
  hilingual-api/src/main/java/org/sopt/controller/diary/api/DiaryController.java
  hilingual-api/src/main/java/org/sopt/controller/diary/service/DiaryService.java
  hilingual-api/src/main/java/org/sopt/controller/diaryfeedback/service/DiaryFeedbackService.java
  hilingual-api/src/main/java/org/sopt/controller/recommend/api/RecommendController.java
  hilingual-api/src/main/java/org/sopt/controller/recommend/service/RecommendService.java
  hilingual-domain/src/main/java/org/sopt/diary/exception/DiaryCoreErrorCode.java
  hilingual-domain/src/main/java/org/sopt/diary/facade/DiaryFacade.java
Labels: 🩷FEAT🩷, 🐰영주🐰

#233 [feat] #220 알림 리스트 확인하기 API 구현 및 #231 팔로우 등록 API 호출 시 유저의 현재 알림 설정 상태에 따라 FeedAlarm 테이블에 알림 쌓이도록 수정
  hilingual-api/src/main/java/org/sopt/controller/follow/service/FollowService.java
  hilingual-api/src/main/java/org/sopt/controller/user/api/UserController.java
  hilingual-api/src/main/java/org/sopt/controller/user/dto/FeedAlarmItemRes.java
  hilingual-api/src/main/java/org/sopt/controller/user/dto/NoticeListItemRes.java
  hilingual-api/src/main/java/org/sopt/controller/user/dto/NotificationItemRes.java
  hilingual-api/src/main/java/org/sopt/controller/user/service/NotificationDeleteJob.java
  hilingual-api/src/main/java/org/sopt/controller/user/service/UserService.java
  hilingual-domain/src/main/java/org/sopt/feedalarm/domain/FeedAlarm.java
  hilingual-domain/src/main/java/org/sopt/feedalarm/facade/FeedAlarmFacade.java
  hilingual-domain/src/main/java/org/sopt/feedalarm/facade/FeedAlarmRetriever.java
  hilingual-domain/src/main/java/org/sopt/feedalarm/facade/FeedAlarmSaver.java
  hilingual-domain/src/main/java/org/sopt/feedalarm/repository/FeedAlarmRepository.java
  hilingual-domain/src/main/java/org/sopt/noticedelivery/facade/NoticeDeliveryFacade.java
  hilingual-domain/src/main/java/org/sopt/noticedelivery/facade/NoticeDeliveryRetriever.java
  hilingual-domain/src/main/java/org/sopt/noticedelivery/repository/NoticeDeliveryRepository.java
  hilingual-domain/src/main/java/org/sopt/user/type/NotificationTab.java
Labels: 🔧FIX🔧, 🩷FEAT🩷, 🐰영주🐰

#235 [feat] #222 피드 좋아요 지정/해제 API 구현
  hilingual-api/src/main/java/org/sopt/controller/feed/api/FeedController.java
  hilingual-api/src/main/java/org/sopt/controller/feed/dto/LikeToggleReq.java
  hilingual-api/src/main/java/org/sopt/controller/feed/dto/LikeToggleRes.java
  hilingual-api/src/main/java/org/sopt/controller/feed/service/FeedService.java
  hilingual-domain/src/main/java/org/sopt/alarmpreference/facade/AlarmPreferenceFacade.java
  hilingual-domain/src/main/java/org/sopt/alarmpreference/facade/AlarmPreferenceRetriever.java
  hilingual-domain/src/main/java/org/sopt/diary/domain/Diary.java
  hilingual-domain/src/main/java/org/sopt/diary/facade/DiaryFacade.java
  hilingual-domain/src/main/java/org/sopt/diary/facade/DiaryUpdater.java
  hilingual-domain/src/main/java/org/sopt/feedalarm/domain/FeedAlarm.java
  hilingual-domain/src/main/java/org/sopt/feedalarm/facade/FeedAlarmFacade.java
  hilingual-domain/src/main/java/org/sopt/feedalarm/facade/FeedAlarmRetriever.java
  hilingual-domain/src/main/java/org/sopt/feedalarm/repository/FeedAlarmRepository.java
  hilingual-domain/src/main/java/org/sopt/likeddiary/facade/LikedDiaryFacade.java
  hilingual-domain/src/main/java/org/sopt/likeddiary/facade/LikedDiaryRemover.java
  hilingual-domain/src/main/java/org/sopt/likeddiary/facade/LikedDiarySaver.java
  hilingual-domain/src/main/java/org/sopt/likeddiary/repository/LikedDiaryRepository.java
Labels: 🩷FEAT🩷, 🐰영주🐰

#236 [fix] #234 1차 전달된 API 수정사항 반영
  hilingual-api/src/main/java/org/sopt/controller/authcode/dto/AuthCodeReq.java
  hilingual-api/src/main/java/org/sopt/controller/authcode/service/AuthCodeService.java
  hilingual-api/src/main/java/org/sopt/controller/usercalendar/api/UserCalendarController.java
  hilingual-api/src/main/java/org/sopt/controller/userprofile/service/UserProfileService.java
  hilingual-auth/src/main/java/org/sopt/jwt/auth/web/JwtAuthenticationFilter.java
  hilingual-domain/src/main/java/org/sopt/alarmpreference/facade/AlarmPreferenceFacade.java
Labels: 🔧FIX🔧, 🐶지은🐶

#242 [feat] 회원탈퇴 API 구현
  hilingual-api/src/main/java/org/sopt/controller/auth/service/AuthService.java
  hilingual-domain/src/main/java/org/sopt/user/facade/UserFacade.java
  hilingual-domain/src/main/java/org/sopt/user/facade/UserRetriever.java
  hilingual-domain/src/main/java/org/sopt/user/repository/UserRepository.java
Labels: 🩷FEAT🩷, 🐶지은🐶

#246 [fix] #245 단어장에 1000개 이상 저장 시도 시 예외 처리 추가
  hilingual-domain/src/main/java/org/sopt/voca/exception/VocaCoreErrorCode.java
  hilingual-domain/src/main/java/org/sopt/voca/exception/VocaLimitExceededException.java
  hilingual-domain/src/main/java/org/sopt/voca/facade/VocaSaver.java
  hilingual-domain/src/main/java/org/sopt/voca/repository/VocaRepository.java
Labels: 🔧FIX🔧, 🐰영주🐰

#252 [fix] #251 3차 API 수정사항 반영
  hilingual-api/src/main/java/org/sopt/controller/auth/service/AuthService.java
  hilingual-api/src/main/java/org/sopt/controller/block/api/BlockController.java
  hilingual-api/src/main/java/org/sopt/controller/block/dto/BlockedListRes.java
  hilingual-api/src/main/java/org/sopt/controller/block/service/BlockService.java
  hilingual-api/src/main/java/org/sopt/controller/feed/service/FeedService.java
  hilingual-api/src/main/java/org/sopt/controller/follow/service/FollowService.java
  hilingual-api/src/main/java/org/sopt/controller/userprofile/api/UserProfileController.java
  hilingual-api/src/main/java/org/sopt/controller/userprofile/dto/UserProfileSummaryRes.java
  hilingual-api/src/main/java/org/sopt/controller/userprofile/service/UserProfileService.java
Labels: 🔧FIX🔧, 🐶지은🐶

#254 [fix] #253 일기 비공개하기 API 호출 시 해당 일기 공감한 유저들 찾아서 LikedDiary DB에서 삭제해주는 로직 추가
  hilingual-api/src/main/java/org/sopt/controller/diary/service/DiaryService.java
  hilingual-domain/src/main/java/org/sopt/likeddiary/facade/LikedDiaryFacade.java
  hilingual-domain/src/main/java/org/sopt/likeddiary/facade/LikedDiaryRemover.java
  hilingual-domain/src/main/java/org/sopt/likeddiary/repository/LikedDiaryRepository.java
Labels: 🔧FIX🔧, 🐰영주🐰

#256 [fix] #255 추천표현 탭 진입 시, 내가 북마크한 단어는 true로 표시되게 수정
  hilingual-api/src/main/java/org/sopt/controller/recommend/service/RecommendService.java
  hilingual-domain/src/main/java/org/sopt/recommend/dto/RecommendWithBookmarkDto.java
  hilingual-domain/src/main/java/org/sopt/recommend/facade/RecommendFacade.java
  hilingual-domain/src/main/java/org/sopt/recommend/facade/RecommendRetriever.java
  hilingual-domain/src/main/java/org/sopt/recommend/repository/RecommendRepository.java
Labels: 🔧FIX🔧, 🐰영주🐰

#258 [fix] #257 일기 삭제할 시 해당 날짜의 status를 DELETED 로 표기
  hilingual-api/src/main/java/org/sopt/controller/diary/service/DiaryService.java
  hilingual-domain/src/main/java/org/sopt/usercalendar/facade/UserCalendarFacade.java
  hilingual-domain/src/main/java/org/sopt/usercalendar/facade/UserCalendarSaver.java
  hilingual-domain/src/main/java/org/sopt/usercalendar/facade/UserCalendarUpdater.java
  hilingual-domain/src/main/java/org/sopt/usercalendar/repository/UserCalendarRepository.java
Labels: 🔧FIX🔧, 🐰영주🐰

#261 [fix] #259 4차 전달된 API 수정사항 반영
  hilingual-api/src/main/java/org/sopt/controller/auth/service/AuthService.java
  hilingual-api/src/main/java/org/sopt/controller/feed/dto/FeedProfileRes.java
  hilingual-api/src/main/java/org/sopt/controller/feed/service/FeedService.java
  hilingual-api/src/main/java/org/sopt/controller/usercalendar/api/UserCalendarController.java
  hilingual-api/src/main/java/org/sopt/controller/usercalendar/service/UserCalendarService.java
  hilingual-api/src/main/java/org/sopt/controller/userprofile/api/UserProfileController.java
  hilingual-api/src/main/java/org/sopt/controller/userprofile/service/UserProfileService.java
  hilingual-domain/src/main/java/org/sopt/alarmpreference/facade/AlarmPreferenceFacade.java
  hilingual-domain/src/main/java/org/sopt/alarmpreference/facade/AlarmPreferenceRemover.java
  hilingual-domain/src/main/java/org/sopt/alarmpreference/repository/AlarmPreferenceRepository.java
  hilingual-domain/src/main/java/org/sopt/block/facade/BlockFacade.java
  hilingual-domain/src/main/java/org/sopt/block/facade/BlockRemover.java
  hilingual-domain/src/main/java/org/sopt/block/repository/BlockRepository.java
  hilingual-domain/src/main/java/org/sopt/diary/facade/DiaryFacade.java
  hilingual-domain/src/main/java/org/sopt/diary/facade/DiaryRemover.java
  hilingual-domain/src/main/java/org/sopt/diary/repository/DiaryRepository.java
  hilingual-domain/src/main/java/org/sopt/feedalarm/facade/FeedAlarmFacade.java
  hilingual-domain/src/main/java/org/sopt/feedalarm/facade/FeedAlarmRemover.java
  hilingual-domain/src/main/java/org/sopt/feedalarm/repository/FeedAlarmRepository.java
  hilingual-domain/src/main/java/org/sopt/follow/facade/FollowFacade.java
  hilingual-domain/src/main/java/org/sopt/follow/facade/FollowRemover.java
  hilingual-domain/src/main/java/org/sopt/follow/repository/FollowRepository.java
  hilingual-domain/src/main/java/org/sopt/likeddiary/facade/LikedDiaryFacade.java
  hilingual-domain/src/main/java/org/sopt/likeddiary/facade/LikedDiaryRemover.java
  hilingual-domain/src/main/java/org/sopt/likeddiary/repository/LikedDiaryRepository.java
  hilingual-domain/src/main/java/org/sopt/topic/facade/TopicFacade.java
  hilingual-domain/src/main/java/org/sopt/usercalendar/facade/UserCalendarFacade.java
  hilingual-domain/src/main/java/org/sopt/usercalendar/facade/UserCalendarRemover.java
  hilingual-domain/src/main/java/org/sopt/usercalendar/facade/UserCalendarRetriever.java
  hilingual-domain/src/main/java/org/sopt/usercalendar/repository/UserCalendarRepository.java
Labels: 🔧FIX🔧, 🐶지은🐶

#263 [fix] #262 기본 이미지는 바인딩하지 않도록 수정
  hilingual-api/src/main/java/org/sopt/controller/feed/dto/FeedProfileRes.java
  hilingual-api/src/main/java/org/sopt/controller/feed/service/FeedService.java
Labels: 🔧FIX🔧, 🐰영주🐰

#268 [fix] #267 프로필 이미지 있을 경우 실제 image url 잘 내려주도록 수정
  hilingual-api/src/main/java/org/sopt/controller/feed/service/FeedService.java
Labels: 🔧FIX🔧, 🐰영주🐰

#274 [fix] #273 단어 상세조회 로직 개선 : 북마크 스냅샷 우선 조회, 원본 조회 fallback 적용
  hilingual-api/src/main/java/org/sopt/controller/voca/dto/res/VocaDetailResponse.java
  hilingual-api/src/main/java/org/sopt/controller/voca/service/VocaService.java
Labels: 🔧FIX🔧, 🐰영주🐰

#281 [fix] #280 1차 버그 리포트 대응
  hilingual-api/src/main/java/org/sopt/controller/auth/service/AuthService.java
  hilingual-domain/src/main/java/org/sopt/userprofile/facade/UserProfileFacade.java
  hilingual-domain/src/main/java/org/sopt/userprofile/facade/UserProfileUpdater.java
  hilingual-domain/src/main/java/org/sopt/userprofile/repository/UserProfileRepository.java
Labels: 🔧FIX🔧, 🐶지은🐶

#284 [fix] #282 새로운 알림 생성 시, 알림 리스트 탭 진입 시 nofity_status
  hilingual-api/src/main/java/org/sopt/controller/admin/service/AdminNoticeService.java
  hilingual-api/src/main/java/org/sopt/controller/user/service/UserService.java
  hilingual-domain/src/main/java/org/sopt/feedalarm/facade/FeedAlarmFacade.java
  hilingual-domain/src/main/java/org/sopt/user/domain/User.java
  hilingual-domain/src/main/java/org/sopt/user/repository/UserRepository.java
Labels: 🔧FIX🔧, 🐰영주🐰

#285 [fix] #283 streak 계산 로직 분기별로 다시 설정
  hilingual-domain/src/main/java/org/sopt/usercalendar/facade/UserCalendarFacade.java
  hilingual-domain/src/main/java/org/sopt/userprofile/facade/UserProfileUpdater.java
Labels: 🔧FIX🔧, 🐬시훈🐬

#287 [fix] #286 total_diaries 계산 방식 변경 (오류 해결)
  hilingual-domain/src/main/java/org/sopt/usercalendar/facade/UserCalendarFacade.java
  hilingual-domain/src/main/java/org/sopt/usercalendar/facade/UserCalendarRetriever.java
  hilingual-domain/src/main/java/org/sopt/usercalendar/repository/UserCalendarRepository.java
  hilingual-domain/src/main/java/org/sopt/userprofile/facade/UserProfileUpdater.java
Labels: 🔧FIX🔧, 🐬시훈🐬

#292 [hotfix] #290 Nullpointer Exception 오류 해결
  hilingual-api/src/main/java/org/sopt/controller/discord/service/WebhookService.java
  hilingual-api/src/main/java/org/sopt/controller/userprofile/api/UserProfileController.java
  hilingual-api/src/main/java/org/sopt/controller/userprofile/service/UserProfileService.java
Labels: 🐶지은🐶, 🎁HOTFIX🎁

#296 [feat] #295 SocialLoginRes에 userId 추가
  hilingual-api/src/main/java/org/sopt/controller/auth/dto/SocialLoginRes.java
  hilingual-api/src/main/java/org/sopt/controller/token/TokenService.java
Labels: 🩷FEAT🩷, 🐶지은🐶
